# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GitHub Actions CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f ci-cd-requirements.txt ]; then pip install -r ci-cd-requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8  --max-complexity=10 --max-line-length=100 --count --show-source --statistics .
    - name: Check types with mypy
      run: |
        mypy --strict --allow-untyped-decorators --ignore-missing-imports .
    - name: Test with pytest
      run: |
        pytest --verbose .
    - name: Generate coverage report
      run: |
        pytest --cov-report=xml:./coverage.xml --cov=stratego tests/
